name: Bug Report
description: Report a bug/crash/error, or some other issue
title: '[Bug]: '
labels: [ "bug" ]
assignees: mosharky
body:
  - type: dropdown
    id: group
    attributes:
      label: Group
      multiple: true
      options:
        - EEK's Beautiful Whiterun
        - JK's Skyrim
        - Rodryk's Dragon Bridge
        - Rogue Unicorn's City Trees
        - The Great Cities of JK's North
        - Skyrim Arrow Overhaul
        - ArteFakes
        - Miscellaneous
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe your issue. Please provide your load order using Load Order Library if applicable.
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Crash report/logs
      description: Paste a link to the crash report, if applicable