name: Patch request
description: Suggest any (like actually any) patch or fix to add to the collection
title: '[Patch Request]: '
labels: [ "patch request" ]
assignees: mosharky
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please make sure all of the following are true
      options:
        - label: Does not already exist
          required: true
        - label: Would only contain ESPs or mesh fixes
          required: true
        - label: Was not already requested
          required: true
        - label: Is not a load order issue (if unsure, its okay to leave unticked)
  - type: textarea
    id: request
    attributes:
      label: Description
      description: Describe your patch request
      placeholder: ex - The combination of mods and why they need a patch
      required: true
