name: Patch request
description: Suggest any (like actually any) patch or fix to add to the collection. Try to be a bit reasonable though.
title: '[Patch Request]: '
labels: [ "patch request" ]
assignees: mosharky
body:
  - type: markdown
    attributes:
      value: Provide a summary of the issue in the Title above

  - type: textarea
    id: request
    attributes:
      label: Describe your patch request
      description: e.g. Why it's needed and what doesn't work
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please acknowledge that the patch you're requesting..
      options:
        - label: Does not already exist
          required: true
        - label: Would only contain ESPs or mesh fixes
          required: true
        - label: Was not already requested
          required: true
        - label: Is not a symptom of a load order issue (if unsure, its okay to leave unticked)
          required: false
        - label: May not be considered
          required: true
