name: Patch request
description: Suggest any patch to add to the collection
title: '[Patch Request]: '
labels: [ "patch request" ]
assignees: mosharky
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please make sure all of the following are true:
      options:
        - label: This patch doesn't already exist
          required: true
        - label: This patch would only contain ESPs or mesh fixes
          required: true
  - type: textarea
    id: request
    attributes:
      label: Request away!
      description: Describe your patch request! Please make sure it isn't a load order issue or a patch that's already been made by me or someone else. You can request any kind of patch, mostly.
      placeholder: 
    validations:
      required: true
